name: Node.js CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/anaa-developers/admin
            git fetch --all
            git reset --hard origin/main
            cp .env.example .env
            npm install --legacy-peer-deps
            npm run build

            # Restart PM2 process
            if pm2 describe anaa-developers-admin > /dev/null; then
              pm2 restart anaa-developers-admin
            else
              pm2 start npm --name "anaa-developers-admin" -- run start
            fi
            pm2 save
